### ISSUE TITLE
Dutch Auction feedback.

### ISSUE THREAD

**Issue by sumit03guha** [ArchanaVaideeswaran/nft-auction#1]
- Redundant import - [import "@openzeppelin/contracts/token/ERC721/ERC721.sol";](https://github.com/ArchanaVaideeswaran/nft-auction/blob/fa6ccdb8917b560e347936ddb1dd774cbf8c096f/contracts/DutchAuction.sol#L5)
- Use safeTransferFrom : https://github.com/ArchanaVaideeswaran/nft-auction/blob/fa6ccdb8917b560e347936ddb1dd774cbf8c096f/contracts/DutchAuction.sol#L122
- Suggestion : The first three requirements are same for both the functions buyAuctionItem and buyAuctionItemEth. The remaining logic is also similar overall. You can create two separate functions for the two different payment methods. So, there will be a single payable buyAuction function, and depending on the payment method redirect to the respective functions. For instance, there will be two private functions(payoutETH and payoutToken).
- Please share the resource from where you have referenced the logic for the Dutch Auction.

**Comment by archana-vy** [comment]
Resources referred for the Dutch auction contract

LooksRare Dutch Auction Strategy: https://github.com/LooksRare/contracts-exchange-v1/blob/master/contracts/executionStrategies/StrategyDutchAuction.sol
Medium blog: https://medium.com/community-economics-by-forte/understanding-auctions-part-1-auction-fundamentals-742acf0edbae
Smart contract programmer blog: https://solidity-by-example.org/app/dutch-auction/
